### ISSUE TITLE
syscoind (syscoin-qt) >100% CPU usage

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#382] opened 2019-12-17 20:53 UTC
If you leave syscoind running (no masternodes, wallet does have transactions that include SYS and SPTs) the process will spike and hold >100% CPU usage after running for >30min. Up until that time process utilization is about 5-15%. Once it goes into the 100%+ state it stays there until you restart it.

**Comment by willyko** [comment] 2019-12-17 20:55
Is this 4.1 only? and which OS

**Comment by sidhujag** [comment] 2019-12-18 03:59
I've reproduced this running for 35 minutes on osx high sierra

**Comment by sidhujag** [comment] 2020-01-03 21:18
i noticed a probleam dealing with peers that have blocks only set, maybe its a miner or some service that doesnt want to propogate txs or they saw how many messages are being sent and thought only to relay blocks
New outbound peer connected: version: 70015, blocks=313088, peer=8 (full-relay)
New outbound peer connected: version: 70015, blocks=313090, peer=33 (block-relay) is what you would see.. the problem was it was still relaying masternode stuff but then rejecting it on other clients who check if the source is blocks only and then disconnecting without banning, once disconnected it would be connected again and try again because its just folllowing the rules, the receiving clients again get masternode stuff and reject/disconnect because the peer is supposed to be blocks only.. I fixed it to take masternode stuff into account, basically blocks only doesnt affect masternode stuff now and only txs are rejected if they are sent through which is what bitcoin did
now i dont see jumping around on my peer list
all peers are 4.1
also messages are now properly displaying the types for masternode msgs as well, instead of 0x0b it will show MNPING etc
it was throwing exception every time and writing out 0x0b which is the code, but now its finding the mapping which didn't exist for masternode opcodes

pushed this fix in https://github.com/syscoin/syscoin/commit/acc5ec35f41e8b8fcf787160991bf5cea84dec45

**Comment by sidhujag** [comment] 2020-01-05 06:25
fixed in 4.1.1

**Closed as completed by sidhujag** 2020-01-05 06:25 UTC
